/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cloud.gltf 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Cloud.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="NurbsCircle" position={[1.316, 2.78, -0.092]} scale={0.669} />
        <group name="NurbsCircle001" position={[0.779, 2.466, 2.529]} rotation={[0.767, -0.315, 0.235]} scale={0.669} />
        <mesh name="Mball020" geometry={nodes.Mball020.geometry} material={materials.Material} position={[-1.158, 1.416, -5.732]} />
        <mesh name="Mball001" geometry={nodes.Mball001.geometry} material={materials['Material.002']} position={[-2.351, -0.181, 6.312]} />
        <mesh name="Mball002" geometry={nodes.Mball002.geometry} material={materials['Material.001']} position={[3.92, 5.846, 0.318]} />
        <mesh name="leaf" geometry={nodes.leaf.geometry} material={materials.standardSurface1} position={[1.316, 2.78, 9.968]} rotation={[-3.076, 0.229, 1.834]} scale={0.165} />
        <mesh name="leaf001" geometry={nodes.leaf001.geometry} material={materials.standardSurface1} position={[-6.033, 1.808, 5.616]} rotation={[2.597, 1.008, -3.044]} scale={0.169} />
        <mesh name="leaf002" geometry={nodes.leaf002.geometry} material={materials.standardSurface1} position={[7.863, 3.353, 7.746]} rotation={[1.878, -0.452, -2.571]} scale={0.174} />
        <mesh name="leaf003" geometry={nodes.leaf003.geometry} material={materials.standardSurface1} position={[11.293, 4.492, 3.322]} rotation={[1.323, -0.548, -2.751]} scale={0.174} />
        <mesh name="leaf004" geometry={nodes.leaf004.geometry} material={materials.standardSurface1} position={[-7.496, 1.033, 2.152]} rotation={[1.634, 0.887, -0.16]} scale={0.169} />
        <mesh name="leaf005" geometry={nodes.leaf005.geometry} material={materials.standardSurface1} position={[11.372, 4.545, -2.755]} rotation={[0.345, -0.382, -2.094]} scale={0.174} />
        <mesh name="leaf006" geometry={nodes.leaf006.geometry} material={materials.standardSurface1} position={[-4.256, 2.285, -8.779]} rotation={[1.38, 0.987, 1.294]} scale={0.174} />
        <mesh name="leaf007" geometry={nodes.leaf007.geometry} material={materials.standardSurface1} position={[5.025, 2.952, -9.432]} rotation={[2.077, -0.6, 0.603]} scale={0.174} />
        <mesh name="leaf008" geometry={nodes.leaf008.geometry} material={materials.standardSurface1} position={[-2.339, -4.173, 9.414]} rotation={[-2.241, 0.52, 1.552]} scale={0.165} />
        <mesh name="leaf009" geometry={nodes.leaf009.geometry} material={materials.standardSurface1} position={[-7.57, -1.727, 3.046]} rotation={[-2.797, 1.396, 3.071]} scale={0.169} />
        <mesh name="leaf010" geometry={nodes.leaf010.geometry} material={materials.standardSurface1} position={[4.276, -2.548, 10.73]} rotation={[2.675, -0.13, -2.339]} scale={0.174} />
        <mesh name="leaf011" geometry={nodes.leaf011.geometry} material={materials.standardSurface1} position={[8.565, 1.085, 9.711]} rotation={[2.229, -0.371, -2.361]} scale={0.174} />
        <mesh name="leaf012" geometry={nodes.leaf012.geometry} material={materials.standardSurface1} position={[-7.677, 0.039, -0.362]} rotation={[1.829, 1.053, 0.479]} scale={0.169} />
        <mesh name="leaf013" geometry={nodes.leaf013.geometry} material={materials.standardSurface1} position={[10.511, 5.132, 5.615]} rotation={[1.254, -0.578, -1.711]} scale={0.174} />
        <mesh name="leaf014" geometry={nodes.leaf014.geometry} material={materials.standardSurface1} position={[-1.571, 8.058, -5.836]} rotation={[1.471, 1.034, 2.038]} scale={0.174} />
        <mesh name="leaf015" geometry={nodes.leaf015.geometry} material={materials.standardSurface1} position={[7.065, 8.605, -2.352]} rotation={[2.877, -0.24, 0.772]} scale={0.174} />
      </group>
    </group>
  )
}

useGLTF.preload('/Cloud.gltf')
